### ISSUE TITLE
Actividad 3, Cuadro comparativo, Edgar Fabian Castro Pérez

### ISSUE THREAD

**Issue by 11042002** [SistemasTecTlaxiaco/actividad-3-cuadro-comparativo-11042002#1]
[Actividad 3, Cuadro Comparativo, Edgar Fabian Castro Pérez.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-cuadro-comparativo-11042002/files/9474888/Actividad.3.Cuadro.Comparativo.Edgar.Fabian.Castro.Perez.pdf)

**Comment by Jaczibeth** [comment]
del 20% sacaste el 20%

**Comment by josealfredo79** [comment]
BIen hecho y revisado..
